version: '3.9'

services:
  app:
    build:
      args:
      # get your user and uid from system
        user: ${USER}
        uid: ${UID:-1000}
      context: .
      dockerfile: ./docker/server/Dockerfile
    container_name: 'app'
    ports:
      - '8020:80'
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - ./docker/server/apache/sites-enabled:/etc/apache2/sites-enabled
      - ./docker/server/php/php.ini:/usr/local/etc/php/conf.d/extra-php-config.ini
      - ./docker/server/php/opcache.ini:/usr/local/etc/php/conf.d/docker-php-ext-opcache.ini
    networks:
      - proxynet

  # postgres:
  #   image: postgres:10.6-alpine
  #   restart: always
  #   container_name: postgres
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_DB=postgres
  #   hostname: postgres
  #   logging:
  #     options:
  #       max-size: 10m
  #       max-file: "3"
  #   ports:
  #     - '5438:5432'
  #   volumes: 
  #     - db_data:/var/lib/postgresql/data
  #     # - ./.docker/db/sql:/docker-entrypoint-initdb.d
  #   networks:
  #     - proxynet

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: db
    ports:
      - 8040:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: homestead
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    volumes: 
      - ./docker/db:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    networks:
      - proxynet

  adminer:
    image: adminer
    container_name: adminer
    restart: unless-stopped
    depends_on:
      - db
    environment:
      ADMINER_DESIGN: nette
      ADMINER_PLUGINS: tables-filter tinymce
    ports:
      - 8030:8080
    networks:
      - proxynet

volumes:
  db_data:

networks:
  proxynet:
    name: mynet
